CREATE TABLE [dbo].[Person](
	[PersonnelId] [int] IDENTITY(1,1) NOT NULL,
	[CitizenId] [nvarchar](max) NULL,
	[TitleName] [nvarchar](max) NULL,
	[TitlePosition] [nvarchar](max) NULL,
	[FirstName] [nvarchar](max) NULL,
	[LastName] [nvarchar](max) NULL,
	[TitleNameEn] [nvarchar](max) NULL,
	[FirstNameEn] [nvarchar](max) NULL,
	[LastNameEn] [nvarchar](max) NULL,
	[DateOfBirth] [datetime] NULL,
	[BloodType] [nvarchar](max) NULL,
	[GenderId] [int] NULL,
	[Gender] [nvarchar](max) NULL,
	[NationId] [nvarchar](max) NULL,
	[Nation] [nvarchar](max) NULL,
	[HomeNumber] [nvarchar](max) NULL,
	[Moo] [int] NULL,
	[Soi] [nvarchar](max) NULL,
	[Street] [nvarchar](max) NULL,
	[SubDistrict] [nvarchar](max) NULL,
	[District] [nvarchar](max) NULL,
	[Province] [nvarchar](max) NULL,
	[ZipCode] [int] NULL,
	[PositionCode] [nvarchar](max) NULL,
	[PersonnelTypeId] [nvarchar](max) NULL,
	[PersonnelType] [nvarchar](max) NULL,
	[PositionTypeId] [nvarchar](max) NULL,
	[PositionType] [nvarchar](max) NULL,
	[Position] [nvarchar](max) NULL,
	[PositionLevelId] [nvarchar](max) NULL,
	[PositionLevel] [nvarchar](max) NULL,
	[StartDate] [datetime] NULL,
	[RetiredDate] [datetime] NULL,
	[RetiredYear] [int] NULL,
	[SectionId] [int] NULL,
	[Section] [nvarchar](max) NULL,
	[DivisionId] [int] NULL,
	[Division] [nvarchar](max) NULL,
	[FacultyId] [int] NULL,
	[Faculty] [nvarchar](max) NULL,
	[Salary] [int] NULL,
	[AdminPositionId] [int] NULL,
	[AdminPositionType] [nvarchar](max) NULL,
	[AdminPosition] [nvarchar](max) NULL,
	[EducationLevelId] [int] NULL,
	[EducationLevel] [nvarchar](max) NULL,
	[TitleEducation] [nvarchar](max) NULL,
	[Education] [nvarchar](max) NULL,
	[Major] [nvarchar](max) NULL,
	[University] [nvarchar](max) NULL,
	[CountryId] [nvarchar](max) NULL,
	[Country] [nvarchar](max) NULL,
	[StartEducationDate] [datetime] NULL,
	[GraduateDate] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[PersonnelId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]



CREATE TABLE [dbo].[PersonEducation](
	[PersonEducationId] [int] IDENTITY(1,1) NOT NULL,
	[CitizenId] [nvarchar](max) NULL,
	[EducationLevelId] [int] NULL,
	[EducationLevel] [nvarchar](max) NULL,
	[TitleEducation] [nvarchar](max) NULL,
	[Education] [nvarchar](max) NULL,
	[Major] [nvarchar](max) NULL,
	[University] [nvarchar](max) NULL,
	[CountryId] [nvarchar](max) NULL,
	[Country] [nvarchar](max) NULL,
	[StartEducationDate] [datetime] NULL,
	[GraduateDate] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[PersonEducationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]